name: 'Digital Ocean Deploy App'
description: 'Deploy an app from an app spec on Digital Ocean'
inputs:
  token:
    description: 'A DigitalOcean personal access token'
    required: true
  spec:
    description: 'Path of the spec file to deploy'
    required: false
    default: './deploy/app.yaml'
  application-id: 'UUID of the (already existing) app to update'
  required: false
runs:
runs:
  using: 'node12'
  main: 'dist/index.js'
